In [2]:
import numpy as np

# Create a 1-D array with 16 elements of integer type

In [3]:
arr = np.arange(1,17,dtype = int)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


# Reshape the create array into 3-D array [where each axis will have more than one element]

In [4]:
arr1 = np.reshape(arr,(2,2,4))
print(arr1)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


# Check the total number of elements in the array

In [5]:
arr2 = np.size(arr)
print(arr2)

16


# Convert the array elements to float type

In [7]:
arr3 = np.array(arr,dtype=float)
print(arr3)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]


# Create an 2-D identity matrrix

In [10]:
arr4 = np.eye(4)
print(arr4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Create an 2-D array which consist of first 10 even numbers[use arange]

In [24]:
arr5 = np.arange(2,22,2).reshape(2,5)
print(arr5)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


# Replace the 1st elements of axis = 0 by first 5 odd numbers

In [30]:
arr5[0]= np.arange(1,11,2)
print(arr5)

[[ 1  3  5  7  9]
 [12 14 16 18 20]]


In [32]:
a = np.array([[2,3,6],[7,8,9]])
print(a[::,1:])

[[3 6]
 [8 9]]


# perform element wise addition [use array A]

In [34]:
arr6 = np.sum(a,axis = 0)
print(arr6)

[ 9 11 15]


# Get the maximum elements in each axis

In [38]:
arr7 = np.max(a,axis = 1)
print(arr7)

[6 9]


# Get the odd Number only from the matrix A [use relational operator]

In [44]:
arr8 = np.array(a % 2 == 1)
print(a[arr8])

[3 7 9]


# Generate the 10 random integers and find the standard deviation and variance

In [50]:
arr9 = np.random.randint(1,11,10)
std1 = np.std(arr9)
var1 = np.var(arr9)
print(arr9)
print(std1)
print(var1)

[ 6  5  2  6 10  2  7  4  3  8]
2.4919871588754225
6.21


# Create a 3-D array [use array(),ndmin] and dispaly the shape of the array

In [52]:
arr10 = np.arange(16)
arr11 = np.array(arr10,ndmin=3)
print(arr11)

[[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]]


In [63]:
B = np.array([[2,5,6],[2,3,2],[1,8,1]])
print(B[::,1:])

[[5 6]
 [3 2]
 [8 1]]


# perform transpose and swapaxis for the matrix B (such that both should result same answer)

In [70]:
arr12 = np.transpose(B)
print(arr12)
print()
arr13 = np.swapaxes(B,axis1 = 0, axis2 = 1)
print(arr13)

[[2 2 1]
 [5 3 8]
 [6 2 1]]

[[2 2 1]
 [5 3 8]
 [6 2 1]]


# perform column-wise concatenation (use matrix B)

In [ ]:
arr14 = np.con